version: '3.7'
services:
  app:
    container_name: topics
    restart: always
    build: .
    ports:
      - '4300:4300'
    volumes:
      - .:/home/ubuntu/app
    links:
      - redis
      - mongo
  mongo:
    container_name: topics-mongo
    image: 'mongo:6'
    ports:
      - '27017:27017'
  redis:
    container_name: topics-redis
    image: 'redis:7'
    ports:
      - '6379:6379'